spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #properties:
      #hibernate:
       #dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true